// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm50L3DXcDbhdnQZ5HH9UELDn6Xl3nC50',
    appId: '1:479217682439:web:039a70109b9d390e9542a2',
    messagingSenderId: '479217682439',
    projectId: 'flutter-chap-app-aca58',
    authDomain: 'flutter-chap-app-aca58.firebaseapp.com',
    storageBucket: 'flutter-chap-app-aca58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQkkKRSGyBXyL7WQcBH79htr9iXHlWZpo',
    appId: '1:479217682439:android:6c5ab42cba4bab5c9542a2',
    messagingSenderId: '479217682439',
    projectId: 'flutter-chap-app-aca58',
    storageBucket: 'flutter-chap-app-aca58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzW7SDjo4wd1Ag39r8RnSnlTNWdy_9bG4',
    appId: '1:479217682439:ios:0b3a822c674f987f9542a2',
    messagingSenderId: '479217682439',
    projectId: 'flutter-chap-app-aca58',
    storageBucket: 'flutter-chap-app-aca58.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
